[20200519] Bowling step01
zunior-team/java-bowling-old pull request #1
Opened 2020-05-19 12:01 UTC by pasudo123

용두사미가 되어버린 코드입니다. 

처음엔 거창하게 시작했는데 코드가 엉망이 되었습니다.

TDD 도 잘 하지 못했습니다. 볼링 게임 구현에 급급해서 TDD 가 어설프게 된 부분도 아쉽네요.

피드백 부탁드립니다..

2020-05-25 00:55 UTC, junwoochoi reviewed
코드 잘 보았습니다!
final 로 상속을 잘 막아놓으신게 인상깊었어요!볼링은 어려웠던 부분이 많아서 조금이라도 도움이 되고자 열심히 코멘트를 달았습니다! ㅎㅎ 👍

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/bowling/BowlingPin.java
> +}
오 볼링 핀까지 객체로 표현하셨네요! 👍  저도 한번 적용해봐야겠습니다.

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/bowling/BowlingPinConstant.java
> +    static final int FIRST_PIN_NUMBER = 1;
접근제한자는 의도적으로 기본으로 하신걸까요? 👀

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/console/Launcher.java
> +        BowlingGame.play();
해당 [코멘트](https://github.com/next-step/java-bowling/pull/76#discussion_r351131115)를 읽어보면 좋을 것 같습니다!

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/console/BowlingGame.java
> +    private static void playBowling(final Player player, final int round){
메소드명과 실제 메소드가 수행하는 일이 알맞지 않은 것 같아요. `playOneRound` 같은 의미가 더 알맞을 것 같네요 :)

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/console/BowlingGame.java
> +        Monitor.printBowlingStatusByPlayer(player.getBowlingBoard());
`BowlingGame` 객체가 컨트롤러의 역할을 하는 것 같은데 맞나요?
해당 객체에서 너무 많은 일을 처리 하고 있는 것 같아요. 
라운드가 끝나기전에 공을 더 던질지에 대한 처리는 다른 객체로 위임하고, 컨트롤러는 공을 던진 결과값을 받아와서 모니터에게 프린트하라는 메시지를 던져주는 정도의 책임만 가지게 해보면 어떨까요?

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/player/Player.java
> +        this.bowlingBoard = bowlingFrames.getBowlingStatusByName(name);
`Player`가 볼링 프레임들과 볼링 보드를 다 가지고 있게 설계하셨군요.
볼링을 생각했을때 보통 볼링 이라는 게임이 있고, 그 안에 `Player`와 프레임이나 보드 들이 존재해야 될 것 같은데 다른 분들은 어떻게 생각하시나요?

이렇게 Player 내부에 볼링게임에 관련된 의존성이 있다고 하면, 물론 현재 저희 상황은 아니지만 볼링이외의 다른 미니게임도 같은 프로젝트내에서 구현해야된다고 가정했을 때,  Player 내부의 모든 볼링 로직들을 떼어내느라 힘들지 않을까 싶기도해요 🤔

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/player/Player.java
> +        return new Player(Objects.requireNonNull(name, "플레이어의 이름은 널이 될 수 없습니다."));
여기서도 null체크를 하고 verifyPlayerName에서도 null체크를 하고 있는데, 혹시 이유가 있으신가요?

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/overturn/OverturnScore.java
> +        if(overturnPins < 0){
0도 매직넘버이긴 하니까 상수로 바꿔봐도 좋을 것 같아요 ㅎㅎ

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/overturn/OverturnScore.java
> +            throw new OverturnScoreCreateException("넘어트린 핀의 개수가 최대 핀의 개수를 넘을 수 없습니다.");
```suggestion
            throw new OverturnScoreCreateException("넘어트린 핀의 개수가 최대 핀의 개수 : " + MAX_PIN_COUNT + "를 넘을 수 없습니다.");
```

지금도 좋지만 이렇게 처리해보면 메시지가 더 명확해질 것 같습니다!

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/trial/Trial.java
> +    }
볼링의 룰이 만약 바뀌어서 한라운드당 6번을 던진다고 하면 메소드를 여섯개로 늘려야할 것 같은데, 더 나은 구조가 있지않을까요? 💭

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/trial/Trial.java
> +        if(trialOrder == TrialOrder.FIRST){
```suggestion
        if(TrialOrder.isEqualTo(trialOrder)){
```
이런식으로 TrialOrder가 직접 판단하는 식이 어떨까요?

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/trial/TrialConstant.java
> +}
사용하지 않는 코드는 과감히 삭제해보아요 😃

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/trial/TrialOrder.java
> +    FIRST, SECOND, THIRD;
시도의 순서를 enum으로 나눈 이유가 있나요? List의 index로도 충분히 확인 가능한 것 같아서요.... 😅

2020-05-25 00:55 UTC, junwoochoi commented on src/test/java/board/FrameStatusTest.java
> +        // System.out.println(Arrays.toString(frameStatus.getFrameStatus().toArray()));
사용하지 않는 코드는 바로바로 삭제하는 게 좋을 것 같습니다! 되돌리고 싶으면 커밋 로그를 활용하면 되니까요 ㅎㅎ

2020-05-25 00:55 UTC, junwoochoi commented on src/test/java/board/ScoreSnapshotTest.java
> +    }
파라미터로 받은 `element`는 어디서 사용하나요...?

2020-05-25 00:55 UTC, junwoochoi commented on src/test/java/board/ScoreStatusTest.java
> +    public void constructor_UseNewKeyword_CreateSuccess(final String name, final List<BowlingFrame> bowlingFrames) {
메소드명은 카멜케이스를 사용하는 게 좋을 것 같습니다.

https://www.javatpoint.com/java-naming-conventions

2020-05-25 00:55 UTC, junwoochoi commented on src/test/java/board/ScoreStatusTest.java
> +    public void constructor_UseNewKeyword_CreateSuccess(final String name, final List<BowlingFrame> bowlingFrames) {
`@ParameterizedTest`를 사용하셨는데 실제 파라미터는 한 종류 뿐이네요

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/frame/BowlingFrame.java
> +    TrialResult decreasePinsAndGetResult(OverturnScore overturnScore);
Query (조회) 와 Command(변경) 가 분리되도록 짜보면 어떨까요?

상태를 변경하는 decrease와 조회하는 get이 한 메소드에서 일어나면 부수효과를 초래할 것 같습니다.

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/board/FrameStatus.java
> +        FRAME_STATUS.addAll(IntStream.rangeClosed(1, 10)
여기서도 매직넘버를 제거해보아요 :)

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/board/ScoreSnapshot.java
> +        if(lastIndex >= 0 &&
if문안에 조건문이 너무 길면 변수 혹은 메소드로 분리하면 가독성이 더 좋을 것 같습니다 😸

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/board/ScoreSnapshot.java
> +        if(String.format(SCORE_EMPTY_FORMAT, StringUtils.EMPTY).equals(snapshot.get(0))){
`객체지향 생활 체조 원칙`을 최대한 의식하며 짜보아요 ㅎㅎ... 저도 어렵지만...

>규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.
규칙 2: else 예약어를 쓰지 않는다.
규칙 3: 모든 원시값과 문자열을 포장한다.
규칙 4: 한 줄에 점을 하나만 찍는다.
규칙 5: 줄여쓰지 않는다(축약 금지)
규칙 6: 모든 엔티티를 작게 유지한다.
규칙 7: 2개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.
규칙 8: 일급 콜렉션을 쓴다.
규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/board/ScoreStatus.java
> +            throw new ScoreStatusCreateException("볼링 점수 프레임의 크기가 10 미만이기 때문에 점수 현황판을 생성할 수 없습니다.");
프레임의 크기가 10 -> 20 으로 변경되면 고칠 곳이 두군데가 생길 것 같은데 상수로 관리해보아용

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/board/ScoreStatus.java
> +                .collect(Collectors.toList()));
```java
List<String> people
         = getPeople().stream()
                      .collect(collectingAndThen(toList(), Collections::unmodifiableList));
```

이런식으로도 사용할 수 있답니다 :)

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/board/ScoreStatus.java
> +                })
.map 내부에 작동로직을 메소드로 빼보면 더 깔끔할 것 같은데 어떨까요?

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/bowling/BowlingPins.java
> +        this.validatePinsCount(decreasePinsCount);
내부의 메소드를 호출할 때 어떨때는 `this.validatePinsCount(decreasePinsCount)` 와 같이 사용하고, `getAlivePinsCount()`처럼 this 없이 호출하는 경우도 있는데 특별한 이유가 없다면 하나로 통일하는게 더 좋을 것 같아요

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/frame/BowlingFrames.java
> +                new HashMap(){{put(frameNumber.newInstance(), trialResult.getTrialResultType());}}
```suggestion
                Collections.singletonMap(frameNumber.newInstance(), trialResult.getTrialResultType())
```
으로도 가능합니당 ㅎㅎ

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/frame/FrameNumber.java
> +                : frameIndex + 1;
```java
	if(currentResultType.isProgress() || currentResultType.isBonus()){
		this.frameIndex += 1;
	}
```

이렇게 하면 삼항연산자 안쓰고 구현 가능할 것 같아요 ㅎㅎ

2020-05-25 00:55 UTC, junwoochoi commented on src/main/java/trial/Trial.java
> +                : TrialResultType.MISS;
```
(alivePins == 0)
                ? TrialResultType.STRIKE
                : TrialResultType.MISS;
```

이 부분 중복해서 자주 사용하는데 메소드로 추출하면 좋을 것 같습니다.

2020-05-27 10:57 UTC, cglee079 reviewed
고생하셨습니다 👍 👍 , 몇가지 코멘트를 남겨봤어요

2020-05-27 10:57 UTC, cglee079 commented on src/main/java/board/ScoreSnapshot.java
> +        return new ScoreSnapshot(new ArrayList(){{ add(String.format(SCORE_EMPTY_FORMAT, StringUtils.EMPTY)); }});
헛, 인자의 `round`는 빼셔도 될거가타용 :)

2020-05-27 10:57 UTC, cglee079 commented on src/main/java/board/ScoreStatus.java
> +                            .addNextBarIfPossible(resultType);
체인형 메소드들이 이곳에서만, 호출되는것같은데
체인형보다 하나의 메소드로 정의해서, 하나의 단위로 사용하는게 좋지 않을까요..?
순서라도 바뀐다면, `snapshot` 모양이 이상해질것같습니다..ㅠ

2020-05-27 10:57 UTC, cglee079 commented on src/main/java/board/ScoreStatus.java
> +
전체적으로 비즈니스랑, 뷰로직이 섞여있는것 같습니다 ㅠ..
여기서, output을 웹상에서 그려주면 문제가 생기지않을까요?
웹상에서 볼링을 한다면, 많은 부분이 변경되지 않을까 생각합니다..

2020-05-27 10:57 UTC, cglee079 commented on src/main/java/frame/FrameNumber.java
> +    }
`Vo`로 `FrameNumber`를 사용하신거같은데, `Vo`는 좀 더 순수해야 하지 않을까 생각합니다.

`FrameNumber`가 `BowlingFrame`에 의존안하는 방법이 더좋을 것 같습니당 👀 
`Vo`가 특정 클래스에 의존한다는것은, ` BowlingFrame` 클래스가 없다면 `Vo`를 사용할 수 없다는것이니까요 ㅠ

2020-05-27 10:57 UTC, cglee079 commented on src/main/java/frame/FrameNumber.java
> +    }
`newInstance()` 보다는 copy의 개념이 맞을것같은데,
적절한 네이밍은 안 떠오르는데 `frameNumber.duplicate()`, `frameNumber.copy()`같은 네이밍은 어떨까요?

2020-05-27 10:57 UTC, cglee079 commented on src/main/java/frame/BowlingFrames.java
> +                                .collect(Collectors.toList())));
요렇게 하면 프레임 개수가 11개가 되지 않나요?? 👀

2020-05-27 10:57 UTC, cglee079 commented on src/main/java/console/BowlingGameConstant.java
> +    public static final int LAST_ROUND_NUMBER = 10;
라운드와 프레임 시작, 마지막 `constant`가 따로 정의되있는데,
프레임 개수와, ROUND 개수가 일관성 없는 상황이 오지 않을까 생각됩니다.

2020-05-27 11:49 UTC, nokchax requested changes
수고하셨습니다ㅎㅎ 코드양이 어마무시하군요.

음 일단 다른 분들과 마찬가지로 분기처리를 없애보도록 해요
그리고 클래스 수가 많아서 복잡도가 높아진거 같아요. 우선은 구조를 잡고
그 이후에 클래스를 나누면서 진행하는 식으로 하시면 조금 수월할 것 같습니다.

2020-05-27 11:49 UTC, nokchax commented on src/main/java/frame/BowlingFrames.java
> +                                        : new NormalFrame())
3항 연산자도 if/else와 동일합니다 요것도 제거해 볼수 있을거 같아요

2020-05-27 11:49 UTC, nokchax commented on src/main/java/frame/BowlingFrame.java
> +public interface BowlingFrame {
BowlingFrame을 구현한 NormalFrame, FinalFrame을 보면 동일한 필드를 가지고있는데요, 이런 경우라면 추상 클래스로 만들어 두고 상속하는게 더 낫지 않을까요?

2020-05-27 11:49 UTC, nokchax commented on src/main/java/player/Player.java
> +        this.bowlingBoard = bowlingFrames.getBowlingStatusByName(name);
볼링 게임만 생각하면 현재 구조도 문제는 없지만, 볼링으로 감싸는게 더 유연한 구조일거 같긴하네요

2020-05-27 11:49 UTC, nokchax commented on src/main/java/trial/Trial.java
> +                : TrialResultType.MISS;
강의내에서는 삼항연산자도 if/else라고 판단하고 있어서
현재 depth가 1이 넘어가요, 개선해봅시다

2020-05-30 04:53 UTC, pasudo123 commented on src/main/java/bowling/BowlingPinConstant.java
> +    static final int FIRST_PIN_NUMBER = 1;
넵 해당 스태틱한 변수를 다른쪽에서도 써서 디폴트로 두었습니다.

2020-05-30 04:56 UTC, pasudo123 commented on src/main/java/console/BowlingGame.java
> +        Monitor.printBowlingStatusByPlayer(player.getBowlingBoard());
넵 중간에 프록시 역할을 해주는 객체가 필요하겠네여 👍

2020-05-30 05:02 UTC, pasudo123 commented on src/main/java/player/Player.java
> +        return new Player(Objects.requireNonNull(name, "플레이어의 이름은 널이 될 수 없습니다."));
널 여부만 해당 오브젝트 리콰이어 쪽에서 검사하고 나머지 공백이나 이름의 길이쪽은 생성자 쪽에서 세부적으로 검사하도록 하였습니다.

2020-05-30 05:02 UTC, pasudo123 commented on src/main/java/player/Player.java
> +        return new Player(Objects.requireNonNull(name, "플레이어의 이름은 널이 될 수 없습니다."));
일반적인 널 여부만 해당 메소드에서 검사하고 나머지 공백이나 이름의 길이등과 같은 세부적인 것들은 생성자에서 하도록 하였습니다.

2020-05-30 05:03 UTC, pasudo123 commented on src/main/java/trial/Trial.java
> +    }
넵 찾아봐야겠어요 ㅎㅎ

2020-05-30 05:05 UTC, pasudo123 commented on src/main/java/trial/TrialOrder.java
> +    FIRST, SECOND, THIRD;
저는 리스트 인덱스에도 화면 볼링 점수뿐만 아니라 콘솔에 출력해주기위한 요소들도 있기 때문에 따로 이넘을 두었습니다.

2020-06-15 12:26 UTC, merged