Step1 볼링 구현해봤습니다.
zunior-team/java-bowling-old pull request #2
Opened 2020-05-20 12:21 UTC by junwoochoi

안녕하세요 볼링 코드 구현해보았습니다.
확실히 다른 과제보다 난이도가 높았던 것 같습니다.

특히 `Tell, Don't Ask`원칙을 지키고 싶었는데 출력로직을 도메인 객체가 가지지 않게 하려고 하다보니 결국 끝났는지 물어보면서 루프를 돌게 되었네요. 다른 분들은 어떻게 짜셨는 지 궁금합니다!

또한 스트라이크, 스페어, 등의 상태를 Enum으로 나누어보려다가, 오히려 더 복잡해지는 것 같기도해서 빼고 HistoryParser에서 처리하도록 했는데 이 객체가 책임이 많은 것 같아서 이부분도 마음에 걸리네요....ㅠㅠ

많은 코멘트 및 토론이 이루어졌으면 좋겠습니다!

2020-05-25 07:53 UTC, gale34 commented on src/main/java/BowlingMain.java
> +            outputView.printBowling(new BowlingPrintDto(bowling));
제가 코드를 제대로 파악한건지 모르겠지만...한번 던질때마다 frameCount가 올라가는 건가요?? 
10개를 쓰러뜨려도 프레임 카운트가 하나 올라가고, 6개를 쓰러뜨려도 하나 올라가는 것 같은데..그러면 나중엔 13 프레임, 14 프레임 출력 문구가 나오지 않나요???

2020-05-25 07:53 UTC, gale34 commented on src/main/java/domain/Pins.java
> +    public static final int NUMBER_OF_PINS = 10;
NUMBER_OF_PINS 라 하면, 현재 핀 갯수를 뜻하는 걸로 오해가 될 것 같습니다! MAX_OF_PINS 같은 이름을 쓰는건 어떨까요??

2020-05-25 07:53 UTC, gale34 commented on src/main/java/view/FrameHistoryParser.java
> +        }
메소드가 좀 긴 것 같습니다. 각 경우일 때 처리하는 부분을 메소드 분리해보는 건 어떨까요??
분기문이 많네요. view layer이긴 합니다만, 분기문을 줄일 방법은 없을까요??

2020-05-25 07:53 UTC, gale34 commented on src/main/java/view/OutputView.java
> +                        parsedFrames.get(8), parsedFrames.get(9)
만약 프레임이 20개가 된다면...코드가 또 늘어날 것 같은데, 출력 부분을 개선할 수는 없을까요??

2020-05-25 11:51 UTC, junwoochoi commented on src/main/java/BowlingMain.java
> +            outputView.printBowling(new BowlingPrintDto(bowling));
@gale34 한번 던질때마다 공은 한번 던져지고 Frame객체의 `isDone()`함수가 `true`일 때는 그 다음 프레임의 쓰러진 핀의 갯수를 입력받고, `false`일 경우에는, 두번째 혹은 세번째 던지기의 쓰러진 핀의 갯수를 입력받습니다. ㅎㅎ

2020-05-25 11:52 UTC, junwoochoi commented on src/main/java/domain/Pins.java
> +    public static final int NUMBER_OF_PINS = 10;
@gale34 앗 넵 `MAX_NUMBER_OF_PINS` 정도로 고쳐보겠습니다 :)

2020-05-25 11:53 UTC, junwoochoi commented on src/main/java/view/FrameHistoryParser.java
> +        }
넵 `view`레이어다보니깐, 도메인 쪽에 비해 허술하게 짜져있는 것 같습니다. 수정할 때 분기문을 줄일 방법들을 좋은 방법들을 찾아봐야할 것 같네요.... 😅

2020-05-25 11:54 UTC, junwoochoi commented on src/main/java/view/OutputView.java
> +                        parsedFrames.get(8), parsedFrames.get(9)
더 좋은 방안 찾아서 수정해보겠습니다 😃

2020-05-25 23:32 UTC, gale34 commented on src/main/java/BowlingMain.java
> +            outputView.printBowling(new BowlingPrintDto(bowling));
아 던지는건 isDone() 사용하는 걸 확인했는데
main함수에서 돌아갈때는 출력에서 프레임 카운트가 계속 올라가는 것 같아서요
![test](https://user-images.githubusercontent.com/24774601/82847861-71cea680-9f2b-11ea-8982-13ffdd223391.png)

2020-05-25 23:54 UTC, junwoochoi commented on src/main/java/BowlingMain.java
> +            outputView.printBowling(new BowlingPrintDto(bowling));
@gale34 앗 그러네요..... 수정이 필요하겠습니다......ㅠㅠ 감사합니다

2020-05-26 00:10 UTC, gale34 commented on src/test/java/domain/NormalFrameTest.java
> +    }
첫 투구가 스트라이크일때, `isDone()`과 `throwBowlingBall()` 테스트 코드도 추가되면 좋을 것 같아요:)

2020-05-26 00:18 UTC, gale34 commented on src/main/java/domain/Pins.java
> +    public void throwBall(int fallenPins) {
개인적으로 Pins 객체의 `throwBall()` 이름이 좀 어색한데요. 
Pins가 볼을 던지는게 아니고, throw된 ball에 쓰러지는게 Pins 아닐까요??

2020-05-26 00:46 UTC, junwoochoi commented on src/main/java/domain/Pins.java
> +    public void throwBall(int fallenPins) {
네... 어색한 것 같아요... 한번 더 좋은 메소드 명을 찾아봐야겠습니다...ㅠ

2020-05-27 00:47 UTC, cglee079 reviewed
고생하셨습니다 👍 👍 ,  몇가지 코멘트를 남겨봤어요 :)!

2020-05-27 00:47 UTC, cglee079 commented on src/main/java/domain/FinalFrame.java
> +public class FinalFrame extends Frame {
- 추상화된것 - 자주 변하지 않는것
- 구체화된것 - 자주 변하는것

둘의 패키지를 구분하면, 수정시에 자주변하지않는것을 컴파일은 안할수 있을것 같아요
오브젝트 내용중 상위정책/하위정책 패키지 분리내용을 공유합니다

https://songii00.github.io/2020/05/08/2020-05-08-OBJECTS%20Item%2015/

2020-05-27 00:47 UTC, cglee079 commented on src/main/java/domain/Pins.java
> +            throw new IllegalArgumentException("fallen pins min value is [" + 0 + "]");
여기도 `ZERO`각 입니다.. ㅎ!

2020-05-27 00:47 UTC, cglee079 commented on src/main/java/domain/FinalFrame.java
> +                .sum();
`frameHistories`를 묶어서 캡슐화 해도 좋을것 같아요,
아니면, 컬렉션 유틸리티 클래스를 정의해서 사용해도 좋을것 같아요!

2020-05-27 00:47 UTC, cglee079 commented on src/main/java/view/FrameHistoryParser.java
> +        }
메소드를 분리하면 좋을것 같아요..!
또, 더 좋은 구조가 있지 않을까요 ㅠㅠ..

2020-05-27 00:47 UTC, cglee079 commented on src/main/java/domain/NormalFrame.java
> +        super();
`super()`는 없어도될거같아용 :)

2020-05-27 00:47 UTC, cglee079 commented on src/main/java/domain/Pins.java
> +        this.countOfPins -= fallenPins;
지금도 좋은데, 

`Pins`를 `value object`로 정의해서, 
부수효과를 줄이는 방향으로하는것도 좋은 방향이 되지 않을까 생각했습니당 :)

2020-05-27 10:33 UTC, nokchax requested changes
고생하셨습니다 ㅠ
비교적 깔끔하긴 하지만, 전반적으로 분기문이 많은 것 같아요, 메소드도 잘게 나눌수 있을거 같구요.
현재 구조라면 나중에 점수 구하는 로직이 추가되면 훨씬 복잡해질 것 같습니다.
이런 시점에서 수정해보셨으면 해요

2020-05-27 10:33 UTC, nokchax commented on src/main/java/domain/FinalFrame.java
> +        return !this.pins.isAllDown();
지금보면 여러개의 if문으로 분기를 태우기 때문에 if else가 여러번 겹쳐있는거나 다름없는거 같아요, 이런 분기를 없앨 수 없을까요?

2020-05-27 10:33 UTC, nokchax commented on src/main/java/utils/StringUtils.java
> +        return (string == null || "".equals(string));
```suggestion
        return (string == null || string.isEmpty());
```
정도면 될거 같아요

2020-05-27 10:33 UTC, nokchax commented on src/main/java/utils/StringUtils.java
> +        return string.chars().allMatch(Character::isAlphabetic);
```suggestion
        return string.chars()
                      .allMatch(Character::isAlphabetic);
```

2020-05-27 10:33 UTC, nokchax commented on src/main/java/BowlingMain.java
> +        int frameCount = 1;
frameCount를 외부에서 관리할 필요가 있을까요?
외부에서는 몰라도 되는 정보 같은데

2020-05-27 10:33 UTC, nokchax commented on src/main/java/domain/Pins.java
> +        }
validate()라는 함수로 뺼수 있을거 같아요

2020-05-27 10:33 UTC, nokchax commented on src/main/java/view/FrameHistoryParser.java
> +        replaces.put(0, "-");
enum 으로 만들수 있지 않을까요?

2020-05-27 10:33 UTC, nokchax commented on src/main/java/view/OutputView.java
> +                )
프레임 수 변경에 취약한 구조인거 같습니다

2020-05-29 00:32 UTC, pasudo123 reviewed
코드 잘보았습니다. 클론해보고 제 코드보다 간결해서 저도 줄여야겠다는 생각이 듭니다.
몇가지 코멘트 사항 남겨두었어요 !

2020-05-29 00:32 UTC, pasudo123 commented on src/main/java/utils/StringUtils.java
> +        return (string == null || "".equals(string));
StringUtils 클래스를 만들었으니, 저는 
```java
private static final String EMPTY = "";
```
를 생각해보았습니다.

2020-05-29 00:32 UTC, pasudo123 commented on src/main/java/view/dto/BowlingPrintDto.java
> +        return frames;
Frames 객체를 보면,
```java
Collections.unmodifiableList 
```

를 이용해서 getFrames() 를 하는데, Dto 객체에서는 getFrames() 시 왜 안하시는지 알 수 있을까요?
물론 저도 안한것 같긴 한데 Dto 는 말 그대로 값전달객체라서 값의 변경여부는 크게 개의치 않는다고 생각해도 될까요.?

2020-05-29 00:32 UTC, pasudo123 commented on src/main/java/domain/Frames.java
> +                .filter(frame -> !frame.isDone())
filter() 메소드의 predicate 인자의 특성으로 메소드 레퍼런스를 이용하여 아래와 같이 표현하는것도 좋겠다는 생각이 들어요.
```suggestion
                .filter(frame::isProceed)
```

2020-05-29 00:32 UTC, pasudo123 commented on src/main/java/view/FrameHistoryParser.java
> +        }
아래와 같이 바꾸는게 가독성상 좋다고 생각이 들어요!
```suggestion
        if (CollectionUtils.isEmpty(frameHistories)) {
            return StringUtils.EMPTY;
        }
```

2020-05-29 00:32 UTC, pasudo123 commented on src/main/java/view/FrameHistoryParser.java
> +        }
맵의 키 값은 히스토리 사이즈를 넣어주고 밸류는 각각 사이즈에 대한 interface 구현체를 넣어주어서 메소드를 처리하도록 하는것도 괜찮을거라 생각이 드는데.. 이게 좋은 방법인지는 모르겠네요.
예를들어)
```java
final Map<Integer, Drawer> drawerMapBySizer = new HashMap<>();
drawerMapBySizer.put(1, new firstDrawer());
drawerMapBySizer.put(2, new secondDrawer());
drawerMapBySizer.put(3, new thirdDrawer());

return drawerMapBySizer.get(size).getStringByDrawer();
```

뭐 이런식이긴 한데, 문득 든 생각을 작성해보았습니다 ㅎㅎ

2020-05-29 00:32 UTC, pasudo123 commented on src/main/java/view/OutputView.java
> +    private static final String FORMAT = "|  %s   |  %s   |  %s   |  %s   |  %s   |  %s   |  %s   |  %s   |  %s   |  %s   |  %s   |";
저도 그냥 이렇게 포맷을 만들어놓고 출력할 껄 그랬나봐요. 애초에 매번 작성할때마다 포맷을 맞추려고 억지로 하다보니 불필요한 코드가 많이 생기고 낭비된 느낌이네요.. ㅜ

2020-05-29 00:32 UTC, pasudo123 commented on src/main/java/domain/Bowling.java
> +        Objects.requireNonNull(player);
Objects.requireNonNull() 메소드에 예외에 대응하기 위한 메시지도 같이 첨부하면 좋겠다는 생각이 듭니다.
NPE 로 물론 발생하겠지만, 어떤 행위의 결과로 인해서 발생했는지 명시적으로 알려주면 좋지 않을까요.?

2020-05-29 01:10 UTC, junwoochoi commented on src/main/java/view/dto/BowlingPrintDto.java
> +        return frames;
앗 제가 dto는 뭔가 힘을빼고 생각해서 그런지, 깜빡하고 안넣은게 맞습니다 ..ㅎㅎ 감사합니다!

2020-05-29 01:10 UTC, junwoochoi commented on src/main/java/domain/Frames.java
> +                .filter(frame -> !frame.isDone())
오 가독성이 훨씬 좋아지겠네요! 고려해보겠습니다!

2020-06-15 12:04 UTC, merged