W04-STEP01 볼링
zunior-team/java-bowling-old pull request #3
Opened 2020-05-20 15:25 UTC by cglee079

잘부탁드립니다...! 어렵네요 ㅠ..

2020-05-27 05:58 UTC, junwoochoi reviewed
테스트 코드를 꼼꼼하게 잘 짜셨네요 :)
NullPointException이 날 수 있는 부분과 의미없는 개행들을 조금 고치면 더 좋을 것 같습니다.
재귀함수로 다음 프레임을 만드는 것도 인상 깊었어요! 코멘트 몇가지 달아보았습니다 😃

2020-05-27 05:58 UTC, junwoochoi commented on src/main/java/com/zuniorteam/bowling/GameBoard.java
> +        if(pitch.equals(Pitch.END)){
`Pitch.END.equals(pitch)`로 쓰는 버릇을 들여야 혹시라도 Null이 나올 수 있는 상황에 대비할 수 있다고 합니다 :-)

2020-05-27 05:58 UTC, junwoochoi commented on src/main/java/com/zuniorteam/bowling/core/frame/Frame.java
> +        assert pinSize != null;
assert는 public메소드에서 사용하지 않는 것으로! 찬구씨한테 배우고 찬구씨한테 써먹기...ㅎㅎ

https://stackoverflow.com/questions/5404754/why-cant-we-use-assertion-for-public-methods

2020-05-27 05:58 UTC, junwoochoi commented on src/main/java/com/zuniorteam/bowling/InputRender.java
> +public class InputRender {
이 [코멘트](https://github.com/next-step/java-bowling/pull/76#discussion_r351131115)도 한번 읽어보면 좋을 것 같아요 :)

2020-05-27 05:58 UTC, junwoochoi commented on src/main/java/com/zuniorteam/bowling/Main.java
> +public class Main {
생성자에 접근제한자를 추가하면 더 좋을 것 같습니다

2020-05-27 05:58 UTC, junwoochoi commented on src/main/java/com/zuniorteam/bowling/core/dto/PitchResult.java
> +    private PinSize fallenPinSize;
final을 붙여도 될 것 같은데 어떻게 생각하시나요?

2020-05-27 05:58 UTC, junwoochoi commented on src/main/java/com/zuniorteam/bowling/core/value/PitchResultType.java
> +            return fallenPinSize.equals(ZERO);
`NullPointException`이 날 수도 있을 것 같아요!

2020-05-27 05:58 UTC, junwoochoi commented on src/main/java/com/zuniorteam/bowling/core/value/PitchResultType.java
> +    public static PitchResultType of(PitchType pitchType, PinSize fallenPinSize, PinSize remainPinSize) {
`remainPinSize`는 `fallenPinSize`를 이용해서 구할 수 있을까요? 파라미터의 갯수를 줄일 수 있을 것 같아서 말씀드려봅니다 👀

2020-05-27 05:58 UTC, junwoochoi commented on src/main/java/com/zuniorteam/bowling/core/pitch/Pitch.java
> +    private Pitch(){};
아래 다른 생성자가 있어서 private으로 지정안하고 그냥 해당 구문 삭제해도 될 것 같아요!

2020-05-27 05:58 UTC, junwoochoi commented on src/main/java/com/zuniorteam/bowling/core/frame/impl/NormalFrame.java
> +
의미없는 개행은 삭제해보아요 👍

2020-05-27 05:58 UTC, junwoochoi commented on src/main/java/com/zuniorteam/bowling/core/value/PitchType.java
> +}
[Item 34. Int 상수 대신 열거 타입을 사용하라.](https://jaehun2841.github.io/2019/02/03/effective-java-item34) 👍 

https://stackoverflow.com/questions/11575376/why-use-enums-instead-of-constants-which-is-better-in-terms-of-software-design

2020-05-27 05:58 UTC, junwoochoi commented on src/main/java/com/zuniorteam/bowling/view/render/PitchResultRender.java
> +    }
알고계시겠지만, 
```java
TOKEN.getOrDefault(pitchResultType, String.valueOf(fallenPinSize));
```
로도 표현 가능합니다 ㅎㅎ

2020-05-27 05:58 UTC, junwoochoi commented on src/test/java/com/zuniorteam/bowling/core/pitch/PitchTest.java
> +        );
👍

2020-05-27 11:11 UTC, cglee079 commented on src/main/java/com/zuniorteam/bowling/InputRender.java
> +public class InputRender {
공유감사합니다 👍 👍

2020-05-27 11:11 UTC, cglee079 commented on src/main/java/com/zuniorteam/bowling/core/frame/Frame.java
> +        assert pinSize != null;
헛.. 생성자에서는 사용해도 되는줄 알앗는뎅,, 아니었네욤,, 감사합니다 👍

2020-05-27 11:11 UTC, cglee079 commented on src/main/java/com/zuniorteam/bowling/core/pitch/Pitch.java
> +    private Pitch(){};
`END` 를 정의하기위해서, `private`메소드를 필요합니다 👀

2020-05-27 11:11 UTC, cglee079 commented on src/main/java/com/zuniorteam/bowling/core/value/PitchResultType.java
> +    public static PitchResultType of(PitchType pitchType, PinSize fallenPinSize, PinSize remainPinSize) {
음, 다음 케이스가 있을것 같아요.
동일한 프레임에 두번째 투구라면 `fallenPinSize`가 3일때 `remainPinSize`를 7이 라 할수 있을까요 👀 ?

2020-05-27 11:12 UTC, nokchax requested changes
수고 하셨습니다.
다른 분들과 마찬가지로 분기를 최대한 없애주는게, 다음 점수 계산을 위해 필요해요
조금 더 고민해보도록 합시다

2020-05-27 11:12 UTC, nokchax commented on src/main/java/com/zuniorteam/bowling/core/frame/Frame.java
> +        }
PinSize 내부에서 처리하도록 하는건 어떨까요?
더하거나, 뺄때 혹은 새 객체를 생성할때 검증해서 책임을 PinSize에 넘기는게 깔끔할거 같아요

2020-05-27 11:12 UTC, nokchax commented on src/main/java/com/zuniorteam/bowling/core/frame/impl/LastFrame.java
> +        }
if else를 제거할 수 있는 방법이 없을까요?

2020-05-27 11:12 UTC, nokchax commented on src/main/java/com/zuniorteam/bowling/core/pitch/Pitch.java
> +    public static final Pitch END = new Pitch();
질문을 이해 못했어요 ㅠ

2020-05-27 11:12 UTC, nokchax commented on src/main/java/com/zuniorteam/bowling/core/value/FrameNumber.java
> +    private final int value;
value 보다는 number 가 낫지 않을까요?

2020-05-27 11:12 UTC, nokchax commented on src/main/java/com/zuniorteam/bowling/core/value/PitchResultType.java
> +    public abstract boolean eq(PitchType pitchType, PinSize fallenPinSize, PinSize remainPinSize);
eq에서 받는 파라미터 수를 줄여서 BiFunction을 사용하는 것이 더 좋겠지만 그게 힘들다면, 아래처럼
```java
@FunctionalInterface
public interface Eq {
    boolean eq(PitchType pitchType, PinSize fallenPinSize, PinSize remainPinSize);
}
```
펑셔널 인터페이스를 만들면
```suggestion
    private final Eq eq;

    PitchResultType(Eq eq) {
        this.eq = eq;
    }
```
```java
GUTTER((pitchType, fallenPinSize, remainPinSize) -> fallenPinSize.equals(ZERO)),
```
깔끔해 질 것 같아요

2020-05-27 11:12 UTC, nokchax commented on src/main/java/com/zuniorteam/bowling/view/render/ScoreRender.java
> +        return drawer.toString();
함수를 잘게 나누어 보아요

2020-05-27 11:12 UTC, nokchax commented on src/main/java/com/zuniorteam/bowling/core/frame/impl/NormalFrame.java
> +        return new Pitch(nextFrame(), FIRST);
여기도 분기를 삭제할 수 있도록 고민해봅시다

2020-05-29 01:24 UTC, pasudo123 reviewed
코드 잘 보았습니다. 저와는 다른 방법으로 볼링게임을 구현하셔서 인상깊었어요.
코멘트 남겨보았습니다.

2020-05-29 01:24 UTC, pasudo123 commented on src/main/java/com/zuniorteam/bowling/core/value/FrameNumber.java
> +    public static final FrameNumber LAST = new FrameNumber(LAST_FRAME_NUMBER_VALUE);
이렇게 하니깐 가독성이 더 좋네요. 저는 FrameNumber 를 만들어놓고, 초기화해준거 같은데.. 배우고 갑니다. 👍

2020-05-29 01:24 UTC, pasudo123 commented on src/main/java/com/zuniorteam/bowling/core/value/PitchResultType.java
> +    public abstract boolean eq(PitchType pitchType, PinSize fallenPinSize, PinSize remainPinSize);
오.. 이렇게 enum 으로 추상메소드 오버라이딩하는 방법도 있군요.. 저도 배워야겠네요 !

2020-05-29 01:24 UTC, pasudo123 commented on src/main/java/com/zuniorteam/bowling/core/pitch/Pitch.java
> +    public static final Pitch END = new Pitch();
저도 이해를 잘 못했어요 ㅠ..

2020-05-29 01:24 UTC, pasudo123 commented on src/main/java/com/zuniorteam/bowling/core/frame/impl/LastFrame.java
> +        }
```suggestion
        if(FIRST.equals(pitchType)){
            return new Pitch(new LastFrame(), BONUS);
        }
```

이렇게만 해줘도 될 것 같아요.

2020-05-29 01:24 UTC, pasudo123 commented on src/main/java/com/zuniorteam/bowling/GameBoard.java
> +        playPitch(firstPitch, username, new ArrayList<>());
재귀를 통해 볼링 게임을 수행한 방식이 인상깊네요 !

2020-06-01 00:33 UTC, cglee079 commented on src/main/java/com/zuniorteam/bowling/core/pitch/Pitch.java
> +    public static final Pitch END = new Pitch();
반환값으로 분기 처리하는데, 세가지를 고민했습니당..

- `null` : 반환값은 `null`은 사용하지 않는것이 권장됩니다.,.
- `Optional` : `Optional`은 느립니다..
- `Keyword` : 해당 타입의 `END` 키워드를 정의했는데, 누군가 다른용도로 사용한다면,, 예를들어 `END`의 객체의 메소드를.. 호출해서 사용하면, 키워드의 의미가..

해당 `END`와 같은 키워드를 정의하는 방법이,  좋은지 잘모르겠어서요..

또 `END`를 사용하니  `final`로 정의한 멤버변수의 초기화 강제성을 잃었네요..
(new Pitch(null, null)은 생성자에 validate()가 문제가 됩니다..)

2020-06-01 00:43 UTC, cglee079 commented on src/main/java/com/zuniorteam/bowling/core/frame/Frame.java
> +        }
말씀하신대로, 음수일 경우 `PinSize`에서 내부에서도 무결성이 검증되어 예외가 발생합니다.

다만, 쓰러진 핀과 남아있는 핀의 개수간의 데이터 일관성은, 
`PinSize`보다는 좀 더 상위수준의 `Frame`의 영역에 더 가깝다 생각해서,
`Frame`에서는 해당 무결성을 검증하도록 하였습니다 👀 !..

2020-06-01 00:44 UTC, cglee079 commented on src/main/java/com/zuniorteam/bowling/core/frame/impl/NormalFrame.java
> +        return new Pitch(nextFrame(), FIRST);
넵 더 고민해보겠습니다 ㅠㅠ..

2020-06-15 12:03 UTC, merged